### PR TITLE
Fix `change:song` event not firing

### LINKED ISSUE #45: `change:song` event not firing in some situations
I know of two situations where `change:song` is not firing
1. When album or artist metadata is not set
2. When the same song is playing but with a different album art

I'll have a PR up soon to fix these two issues

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #45 

This creates a wrapper function that safely fetches the `textContent` of a possibly null or empty element.

Also handles the albumArt changing without the metadata changing

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -55,6 +55,11 @@ function bind(context, fn) {
   };
 }
 
+// Define textContent method to safely fetch textContent of unknown elements
+function textContent(elem, defaultText) {
```
Comment (twolfson) [inline lib/main.js]: Can we rename this to `getTextContent`? It will feel more semantic to me; right now I am not sure whether this would be a get/set/something else

File: lib/main.js [hunk 2]
```diff
@@ -55,6 +55,11 @@ function bind(context, fn) {
   };
 }
 
+// Define textContent method to safely fetch textContent of unknown elements
```
Comment (twolfson) [inline lib/main.js]: Grammar fix here: "textContent of" should be "textContent from". One doesn't really "fetch a ball of the ground", instead you "fetch a ball from the ground".

File: lib/main.js [hunk 3]
```diff
@@ -404,12 +410,13 @@ proto.hooks = {
             var songInfo = that.playback.getSongInfo();
             // Make sure that this is the first of the notifications for the
             // insertion of the song information elements.
-            if (lastTitle !== songInfo.title || lastArtist !== songInfo.artist || lastAlbum !== songInfo.album) {
+            if (lastTitle !== songInfo.title || lastArtist !== songInfo.artist || lastAlbum !== songInfo.album || lastArt !== songInfo.art) {
```
Comment (twolfson) [inline lib/main.js]: This line is too long and causing linting to fail. Can you break it into multiple lines?

``` js
if (lastTitle !== songInfo.title || lastArtist !== songInfo.artist ||
    lastAlbum !== songInfo.album || lastArt !== songInfo.art) {
  that.emit('change:song', songInfo);
```

**Comment by twolfson** [comment]
High level content looks good, left some feedback to improve maintenance in the future

**Comment by MarshallOfSound** [comment]
Updated PR

File: dist/gmusic.js [hunk 4]
```diff
@@ -222,9 +227,9 @@ proto.playback = {
 
   getSongInfo: function () {
     var songInfo = {
-      title: this.doc.getElementById(SELECTORS.info.titleId).textContent || 'Unknown',
-      artist: this.doc.getElementById(SELECTORS.info.artistId).textContent || 'Unknown',
-      album: this.doc.querySelector(SELECTORS.info.albumSelector).textContent || 'Unknown',
+      title: getTextContent(this.doc.getElementById(SELECTORS.info.titleId), 'Unknown Title'),
```
Comment (twolfson) [inline dist/gmusic.js:230]: Mmmm, proper nouns =P

**Comment by twolfson** [comment]
Looks good to me, :shipit:
