### PR TITLE
Cache observer values for more robust events

### LINKED ISSUE #29: Repeat/Shuffle observer firing multiple times
Following on from a a discussion [here](https://github.com/radiant-player/radiant-player-mac/pull/402#issuecomment-171623290), I've noticed the repeat/shuffle observer is being fired multiple times on change.  

As @twolfson suggests, this could be due to multiple attributes changing - I guess this could relate to multiple instances of each button around the app, where changing one changes several others?

https://github.com/gmusic-utils/gmusic.js/blob/4.0.3/lib/main.js#L366-L386

This isn't a bug per say as the data isn't wrong, but figured it could be worth logging as a note to look into a bit further at some point for the sake of optimization.

### LINKED ISSUE #33: on('change:rating') not firing from outside changes
As best as I can tell, `on('change:rating')` isn't firing if the user manually changes the rating of a song.  

Code in use: https://github.com/radiant-player/radiant-player-mac/blob/gmusic-utils/radiant-player-mac/js/main.js.

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This implements the suggested solution for #33 for the rating, shuffle, and repeat observers.  Interestingly this was already set up for playback mode and song observers, so this PR rounds out the rest.  This should also fix an issue where the `change:repeat` and `change:shuffle`.

Fixes #29.
Fixes #33.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Let me see if I can debug that test failure...

**Comment by MarshallOfSound** [comment]
Do you have access to the browserstack account, you can see console logs and a video of the tests?

**Comment by jacobwgillespie** [comment]
I don't think I have access, no - that would be kinda sweet :)

**Comment by MarshallOfSound** [comment]
I just sent an invite to your gmail account that is registered with github. :+1: 

You can also interupt the test and dive into an interactive session with the browser :+1:

**Comment by jacobwgillespie** [comment]
Sweet, thanks, I got in.  Now I just have to figure out which test is which :smile:

**Comment by MarshallOfSound** [comment]
@jacobwgillespie From my quick look, I believe this failure is to be expected.

This code (correct me if I'm wrong here) only fires once per change and if it doesn't change it doesn't fire.

The old code fired a change even when a change did not occur, this lead to a "down vote -> down vote" being considered a change?  I think the numbers just have to be changed, not sure though so double check the theory :cactus: :tada:

**Comment by jacobwgillespie** [comment]
Yeah, I changed the test - I'm only seeing one call to `toggleShuffle` so I'd only expect `shuffleCount` to be `1`.  Not sure why it was 2 before, but that's been fixed now.

**Comment by MarshallOfSound** [comment]
Tests are passing, now it's just linting issues :+1:

**Comment by twolfson** [comment]
omg omg omg

**Comment by jacobwgillespie** [comment]
Linting passing locally now - let's see what Travis thinks...

File: lib/main.js [hunk 1]
```diff
@@ -459,23 +473,23 @@ proto.hooks = {
...
         var target = m.target;
-        // If we are looking at a rating button and it's selected, emit a notification
-        // DEV: Prevent selection of container and "remove-circle-outline" button
-        // jscs:disable maximumLineLength
-        // Good:
-        //   <paper-icon-button icon="sj:thumb-up-outline" data-rating="5" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-icon-button-0" title="Thumb-up" aria-label="Thumb-up"></paper-icon-button>
-        // Bad:
-        //   <div id="playerSongInfo" style=""></div>
-        //   <paper-icon-button icon="remove-circle-outline" data-rating="0" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-icon-button-0"></paper-icon-button>
-        // jscs:enable maximumLineLength
```
Comment (twolfson) [inline lib/main.js:473]: I feel like these comments would be good to preserve. Can we keep them?

It will be practical when Google changes their HTML on us and we have no idea what our original selectors were based on.

Comment (jacobwgillespie) [inline lib/main.js:473]: Yep, returned

**Comment by twolfson** [comment]
Left a comment about preserving comments. Looks good otherwise. Nice work :+1: 

With respect to the shuffle count, I'm going to guess I didn't see the test failing when I bumped the count to 2 yet it failed when it was at 3

**Comment by jacobwgillespie** [comment]
Sweet - so if it passes tests you want me to merge?

And will you release it soon?  No particular rush, but I'm out of the loop on how we're doing releases in this project.  :smile:

**Comment by twolfson** [comment]
One note would be it would be nice to abstract the `diff/emit` logic somehow. We could prob do something like Backbone with a `.set` but then we are prob overengineering (e.g creating an object to track state when we don't really want to track state).

http://backbonejs.org/#Model-set

https://github.com/jashkenas/backbone/blob/1.3.2/backbone.js#L461-L516

**Comment by twolfson** [comment]
But consider that to be a pedantic thought and nothing we need to implement

File: lib/main.js (hunk 1 above)
Comment (twolfson) [inline lib/main.js:473]: Sweet, thanks =)

**Comment by twolfson** [comment]
Releases are documented here:

https://github.com/gmusic-utils/gmusic.js/blob/4.1.0/CONTRIBUTING.md#release-process

You should be good to land once Travis approves. Buuuut, I think you aren't an owner on `npm`. What's your `npm` user?

**Comment by twolfson** [comment]
Oh hey, I never landed #31. I'm going to sneak that in ;)

**Comment by jacobwgillespie** [comment]
npm username is `jacobwgillespie`.  Sounds good.

Sometime we should implement publishing from a bot npm user via Travis :)

**Comment by jacobwgillespie** [comment]
Rebased with your #31.

**Comment by twolfson** [comment]
Alright, you are now an owner on npm :tada: 

https://www.npmjs.com/package/gmusic.js

With respect to a bot, I'm open to it but it's prob more trouble than it's worth (e.g. need to handle CHANGELOG updating, git tagging, handle errors, we don't release too frequently)

**Comment by twolfson** [comment]
No need to worry about rebasing on this repo, I don't mind merge commits. Heck, most of the original commits weren't even squashed =X

**Comment by jacobwgillespie** [comment]
Sweet :tada: 

Yeah, with foundry it might not make sense to get bot publishing...  On radiant I've got a basic prepare-release script that does everything but the "npm publish" (app build and release), then Travis does that for tagged commits.  Might not fit into the workflow here.

**Comment by jacobwgillespie** [comment]
`4.2.0` is live!  Thanks for the help!

**Comment by twolfson** [comment]
:tada: :tada: :tada:

**Comment by twolfson** [comment]
Tangent: How do you handle changelogs in Radiant's workflow?

**Comment by jacobwgillespie** [comment]
We always have an `[unreleased]` tag at the top of the changelog: https://github.com/radiant-player/radiant-player-mac/blob/master/CHANGELOG.md#unreleased

The prepare-release script updates that tag to the version you specify when it's building out the new release, with some sanity checks to make sure everything looks okay: https://github.com/radiant-player/radiant-player-mac/blob/master/scripts/prepare-release.sh#L71-L98

So essentially you're supposed to have your changelog entries staged under [unreleased] before release - preferably they were added alongside their original PRs.

**Comment by twolfson** [comment]
Ah, k. That's a nice approach. Thanks for the info =)
